### ISSUE TITLE
Foreca v3.3.1

### ISSUE THREAD

**Issue by Orlandoxx** [E2OpenPlugins/e2openplugin-Foreca#78]
Hello, 
after pressing 'Menu' button ("Maps") nothing else works except 'Eumetsat'. Can you check it please ?

- "Weather map Video"
- "Showerradar Video"
- "Temperature Video"
- "Cloudcover Video"
- "Air pressure"

**Comment by MrServo** [comment]
In the (long) meantime, the access had changed again and the satellite images are all working again. However, only in the 'python3' branch: https://github.com/E2OpenPlugins/e2openplugin-Foreca/pull/79
In my opinion issue can be closed...

**Comment by Orlandoxx** [comment]
Thanx.
